workflows:
  ios-build:
    name: Build IPA iOS ExploitApp
    max_build_duration: 60
    environment:
      vars:
        XCODE_PROJECT: "ExploitApp.xcodeproj"
        XCODE_SCHEME: "ExploitApp"
        EXPORT_OPTIONS_PLIST: "export/ExportOptions.plist"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Nettoyage du projet
        script: |
          xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME"
      - name: Build et archive
        script: |
          xcodebuild archive -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -archivePath "$CM_BUILD_DIR/ExploitApp.xcarchive" -destination 'generic/platform=iOS' ONLY_ACTIVE_ARCH=YES DEVELOPMENT_TEAM="$CM_DEVELOPMENT_TEAM"
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath "$CM_BUILD_DIR/ExploitApp.xcarchive" -exportPath "$CM_BUILD_DIR/export" -exportOptionsPlist "$EXPORT_OPTIONS_PLIST"
    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
    publishing:
      email:
        recipients:
          - "your@email.com"
        notify:
          success: true
          failure: true
